general_settings:
  master_key: sk-wqn0xwq_vha4MVM2yzw
  default_model: zoi-coder
  fallback_models: [zoi-coder, zoi-planner]
  timeout: 300
  request_timeout: 120

litellm_settings:
  set_verbose: false
  drop_params: true
  disable_provider_health_check: true

router_settings:
  routing_strategy: "simple"
  enable_pre_call_checks: false
  disable_cooldowns: true
  allowed_fails: 100
  enable_fallbacks: false
  
model_list:
  - model_name: zoi-coder
    litellm_params:
      custom_llm_provider: openai
      model: qwen/qwen3-14b
      api_base: http://ioz.zoi.local:1234/v1
      api_key: sk-no-key-required
    model_info:
      mode: chat
      
  - model_name: zoi-planner
    litellm_params:
      custom_llm_provider: openai
      model: qwen/qwen3-coder-30b
      api_base: http://astra.zoi.local:1234/v1
      api_key: sk-no-key-required
    model_info:
      mode: chat

  - model_name: zoi-embed
    litellm_params:
      custom_llm_provider: openai
      model: text-embedding-nomic-embed-text-v1.5
      api_base: http://astra.zoi.local:1234/v1
      api_key: sk-no-key-required
    model_info:
      mode: embedding