version: 1
metadata:
  name: Traefik Forward Authentication
  description: Automatic setup for Traefik forward authentication proxy provider and application

entries:      
  # Forward Auth Application  
  - model: authentik_core.application
    identifiers:
      slug: traefik-forward-auth
    attrs:
      name: Traefik Forward Auth
      slug: traefik-forward-auth
      provider: !Find [authentik_providers_proxy.proxyprovider, [name, "traefik-forward-auth-provider"]]
      meta_launch_url: blank://blank
      meta_description: Traefik Forward Authentication Handler
      policy_engine_mode: any
      
  # Assign to embedded outpost
  - model: authentik_outposts.outpost
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      providers:
        - !Find [authentik_providers_proxy.proxyprovider, [name, "traefik-forward-auth-provider"]]
